service: zani

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'ap-northeast-2'}
  logRetentionInDays: 30
  versionFunctions: false
  timeout: 30
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'table/claude.${self:provider.stage}.commit'
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'table/claude.${self:provider.stage}.user'
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'table/claude.${self:provider.stage}.repository'
  deploymentBucket:
    name: claude.serverless.${self:provider.region}.deploys
    serverSideEncryption: AES256
  environment:
    TZ: Asia/Seoul
    NODE_ENV: ${opt:stage, 'development'}
  tracing:
    lambda: true
    apiGateway: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  webhook:
    handler: src/api/webhook/controller.exec
    description: 'github webhook'
    events:
      - http:
          path: /u/{uid}/hooks
          method: post
          cors: false
          request:
            parameters:
              paths:
                uid: true

  notifier:
    handler: src/task/notifier.exec
    description: 'send notification about commit'
    events:
      - schedule:
          rate: cron(00 15 * * ? *)
          description: '1차 안내 메시지 발송 (KST 00시 00분)'
          input:
            type: 'nudge'
      - schedule:
          rate: cron(30 16 * * ? *)
          description: '경고 메시지 발송 (KST 01시 30분)'
          input:
            type: 'warning'
      - schedule:
          rate: cron(00 17 * * ? *)
          description: '시간 초과 안내 메시지 발송 (KST 02시 00분)'
          input:
            type: 'detect'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: 'npm'
